# Email:    admin@example.com
# Password: changeme
# https://www.bilibili.com/read/cv14665485/
# https://www.cnblogs.com/jawide/p/16527689.html
# https://github.com/NginxProxyManager/nginx-proxy-manager/issues/259
version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  data: {}
  letsencrypt: {}
